import burger from "../assets/images/food-items/burger.jpeg";

export const FoodItems = [
	{
		title: "Mutton Kacchi",
		category: "Kacchi",
		price: 300,
		rating: 4.5,
		image: burger,
	},
	{
		title: "Vegetarian Pasta",
		category: "Pasta",
		price: 250,
		rating: 4.2,
		image: burger,
	},
	{
		title: "Spicy Seafood Curry",
		category: "Curry",
		price: 400,
		rating: 4.7,
		image: burger,
	},
	{
		title: "Chicken Shawarma",
		category: "Shawarma",
		price: 180,
		rating: 4.0,
		image: burger,
	},
	{
		title: "Margherita Pizza",
		category: "Pizza",
		price: 320,
		rating: 4.6,
		image: burger,
	},
	{
		title: "Fruit Salad",
		category: "Salad",
		price: 150,
		rating: 4.3,
		image: burger,
	},
	{
		title: "Beef Tacos",
		category: "Tacos",
		price: 220,
		rating: 4.4,
		image: burger,
	},
	{
		title: "Cheeseburger",
		category: "Burger",
		price: 280,
		rating: 4.8,
		image: burger,
	},
	{
		title: "Chicken Caesar Salad",
		category: "Salad",
		price: 200,
		rating: 4.5,
		image: burger,
	},
	{
		title: "Sushi Platter",
		category: "Sushi",
		price: 450,
		rating: 4.9,
		image: burger,
	},
	{
		title: "Penne Arrabiata",
		category: "Pasta",
		price: 260,
		rating: 4.1,
		image: burger,
	},
	{
		title: "Vegetable Biryani",
		category: "Biryani",
		price: 280,
		rating: 4.6,
		image: burger,
	},
	{
		title: "Chocolate Fondue",
		category: "Dessert",
		price: 180,
		rating: 4.3,
		image: burger,
	},
	{
		title: "Greek Salad",
		category: "Salad",
		price: 190,
		rating: 4.2,
		image: burger,
	},
	{
		title: "Paneer Tikka",
		category: "Appetizer",
		price: 220,
		rating: 4.5,
		image: burger,
	},
	{
		title: "Chicken Alfredo Pasta",
		category: "Pasta",
		price: 300,
		rating: 4.7,
		image: burger,
	},
	{
		title: "Caesar Wrap",
		category: "Wrap",
		price: 210,
		rating: 4.4,
		image: burger,
	},
	{
		title: "Shrimp Scampi",
		category: "Seafood",
		price: 380,
		rating: 4.6,
		image: burger,
	},
	{
		title: "Falafel Platter",
		category: "Platter",
		price: 240,
		rating: 4.0,
		image: burger,
	},
	{
		title: "Mango Sticky Rice",
		category: "Dessert",
		price: 160,
		rating: 4.8,
		image: burger,
	},
	{
		title: "BBQ Chicken Wings",
		category: "Appetizer",
		price: 180,
		rating: 4.5,
		image: burger,
	},
	{
		title: "Caprese Salad",
		category: "Salad",
		price: 200,
		rating: 4.2,
		image: burger,
	},
	{
		title: "Tandoori Chicken",
		category: "Appetizer",
		price: 250,
		rating: 4.6,
		image: burger,
	},
	{
		title: "Vegetarian Burrito",
		category: "Burrito",
		price: 230,
		rating: 4.3,
		image: burger,
	},
	{
		title: "Lemon Garlic Shrimp",
		category: "Seafood",
		price: 320,
		rating: 4.7,
		image: burger,
	},
	{
		title: "Chicken Fajitas",
		category: "Fajitas",
		price: 270,
		rating: 4.5,
		image: burger,
	},
	{
		title: "Tomato Basil Bruschetta",
		category: "Appetizer",
		price: 150,
		rating: 4.1,
		image: burger,
	},
	{
		title: "Teriyaki Salmon",
		category: "Seafood",
		price: 350,
		rating: 4.9,
		image: burger,
	},
	{
		title: "Veggie Wrap",
		category: "Wrap",
		price: 190,
		rating: 4.4,
		image: burger,
	},
	{
		title: "Pesto Chicken Panini",
		category: "Panini",
		price: 280,
		rating: 4.6,
		image: burger,
	},
	{
		title: "Avocado Salad",
		category: "Salad",
		price: 210,
		rating: 4.3,
		image: burger,
	},
	{
		title: "Szechuan Noodles",
		category: "Noodles",
		price: 240,
		rating: 4.5,
		image: burger,
	},
	{
		title: "Chicken Gyro",
		category: "Gyro",
		price: 260,
		rating: 4.7,
		image: burger,
	},
	{
		title: "Raspberry Cheesecake",
		category: "Dessert",
		price: 180,
		rating: 4.2,
		image: burger,
	},
	{
		title: "Cajun Shrimp Pasta",
		category: "Pasta",
		price: 320,
		rating: 4.8,
		image: burger,
	},
	{
		title: "Eggplant Parmesan",
		category: "Vegetarian",
		price: 230,
		rating: 4.4,
		image: burger,
	},
	{
		title: "Chicken Satay",
		category: "Appetizer",
		price: 200,
		rating: 4.6,
		image: burger,
	},
	{
		title: "Shrimp Po' Boy",
		category: "Sandwich",
		price: 250,
		rating: 4.5,
		image: burger,
	},
	{
		title: "Strawberry Shortcake",
		category: "Dessert",
		price: 160,
		rating: 4.3,
		image: burger,
	},
	{
		title: "Thai Green Curry",
		category: "Curry",
		price: 380,
		rating: 4.9,
		image: burger,
	},
	{
		title: "Quinoa Salad",
		category: "Salad",
		price: 190,
		rating: 4.2,
		image: burger,
	},
];
